### ISSUE TITLE
[EPIC] WGS <-> UTM Projection Support

### ISSUE THREAD

**Issue by jarmak-nv** [rapidsai/cuspatial#1023]
## Overview and Description
It's nearly impossible to talk about geospatial operations without mentioning projections. cuSpatial seeks to enables users to seamlessly work with spatial data in various coordinate systems, ensuring compatibility and interoperability among diverse datasets, beginning with the common WGS <-> UTM coordinate systems.

Accurate projections are essential for precise spatial analysis and visualization, as they minimize spatial distortions and preserve the spatial relationships between features. By incorporating projection support, cuSpatial will enhance its utility and broaden its appeal.

This epic covers multiple areas of the library, and is scoped to only include UTM <-> WGS conversion to ensure timely delivery. 

**Target start:** During the 23.06 development cycle
**Target release:** Release 23.08

## Requirements
For successful completion, this epic needs:
```[tasklist]
- [ ] https://github.com/rapidsai/cuspatial/issues/1100
- [ ] https://github.com/rapidsai/cuspatial/issues/1127
- [ ] https://github.com/rapidsai/cuspatial/issues/1139
- [x] A consensus on how to handle projections at the user level
- [ ] https://github.com/rapidsai/cuspatial/issues/1213
- [x] Python notebook demonstrating UTM <-> WGS transformation
- [ ] https://github.com/rapidsai/cuspatial/issues/1215
- [ ] https://github.com/rapidsai/cuspatial/issues/1239
```

## Considerations
Handling projectsions at the user level can be done many ways. It could mean a mirroring [geopandas crs handling](https://geopandas.org/en/stable/docs/user_guide/projections.html). It also might be an external function, requiring users to track CRS on their own - or somewhere in between.

## Related Issues
This epic will close:
- https://github.com/rapidsai/cuspatial/issues/572
- https://github.com/rapidsai/cuspatial/issues/453

This epic makes progress on:
- https://github.com/rapidsai/cuspatial/issues/55
- https://github.com/rapidsai/cuspatial/issues/54
