### ISSUE TITLE
[DOC] Improve C++ developer documentation

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#598]
We would like to improve cuSpatial's developer documentation to make it easier to contribute to cuSpatial.

I think we should follow the lead of cuDF,  which has a relatively comprehensive set of documentation for developers.  That means providing the following documents.

- [x] [cpp/docs/DEVELOPER_GUIDE.md](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/docs/DEVELOPER_GUIDE.md): a guide for developers contributing C++ / CUDA C++ code to cuSpatial, covering key terms, directory structure and file naming, code and documentation style and formatting, key data structures, API style (e.g. parameters, inputs and outputs), error handling, deprecation guidelines, and data types. #606 
- [x] [cpp/docs/DOCUMENTATION.md](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/docs/DOCUMENTATION.md): a guide to writing and building libcuspatial documentation using Doxygen. #667 
- [x] [cpp/docs/TESTING.md](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/docs/TESTING.md): A guide to writing unit tests for libcuspatial. #672 
- [x] [cpp/docs/BENCHMARKING.md](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/docs/BENCHMARKING.md): A guide to writing unit benchmarks for libcuspatial. #672
